### ISSUE TITLE
Stream audio through a (virtual) microphone using NodeJS

### ISSUE THREAD

**Issue by joaocarlospf** [Bernard-Borg/SoundboardApp#1]
Stream audio through a (virtual) microphone using NodeJS.

**Comment by joaocarlospf** [comment]
For those who might be interested in helping with this issue, [Open Coders](https://opencoders.club) is supporting this issue with a USD 50 bonus for those who resolve it using the service and provide feedback. Here is the link of the request:

https://app.opencoders.club/dev-requests/16

Obs: Open Coders is still closed for invited developers. So you can register there and wait for approval.

**Comment by Bernard-Borg** [comment]
This will no longer be needed since the project is in the process of being switched over to tauri
